project:
  type: website
  output-dir: docs

website:
  title: "Orin Crouse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Goalies.qmd
        text: Goalies
      - href: ChainPulse.qmd
        text: Crypto
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

