project:
  type: website
  output-dir: docs

website:
  title: "Orin Crouse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Goalies.qmd
        text: Goalies
      - href: Crypto.qmd
        text: Crypto
      - href: Big Pharma.qmd
        text: Big Pharma
format:
  html:
    theme: cosmo
    mainfont: arial
    fontcolor: "#1e3d09"
    linkcolor: "#26146e"
    monofont: times new roman
    css: styles.css
    toc: true

editor: visual

