project:
  type: website
  output-dir: docs

website:
  title: "Orin Crouse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Goalies.qmd
      - ChainPulse.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

